### ISSUE TITLE
Files to include in the end-user package (readme file, license, etc)

### ISSUE THREAD

**Issue by SunyataZero** [SunyataZero/mindfulness-at-the-computer#17]
* Readme - We may want to add a readme.txt file as well, this file would be directed towards the end-user (The README.md file in this project is written for tech people, and it's not included in the end-user package - after having built with pyinstaller)
* License

Todo list:
* [ ] Look at what other projects are doing

**Comment by SunyataZero** [comment]
One option is to include a readme.txt file as well as the .md file, and then include this in the package built by pyinstaller

**Comment by SunyataZero** [comment]
I've now asked a question here about this: https://softwareengineering.stackexchange.com/questions/360567/what-non-essential-files-should-be-included-in-end-user-package

**Comment by JedMeister** [comment]
I was almost tempted to reply to your SE question, but seeing as I can't really give you anything other than my personal opinion (which may or may not be legitimate - whilst I'm a "developer" of sorts, I'm not really a proper "programmer"). 

As someone who spends a lot of time at the commandline and from the perspective of a developer (see above) I would suggest that including a readme and licence are highly desirable. On the downside, they are additional files to include and may not get read. But on the upside, they are plain text files which are extremely small to start with and compress incredibly well. And as a developer, the quicker and easier I can find the info I'm after (such as the licence and/or a basic understanding of what the software is meant to achieve) IMO the upsides far outweigh the downsides. 

IMO contributors is far less important. TBH, we (as in TurnKey Linux) don't even keep a record of contributors (although perhaps we should). We make a point of directly thanking them explicitly at the time and often recap and highlight their efforts in blog posts, but essentially, we just let their commits speak for themselves.

**Comment by SunyataZero** [comment]
I've now included both the readme and license files in the end-user package, closing this issue. Thank you @JedMeister for your help!
