### ISSUE TITLE
Suggestions for wiki

### ISSUE THREAD

**Issue by andy5995** [SunyataZero/mindfulness-at-the-computer#19]
@SunyataZero writes:

>Any recommendations for how to use the github wiki? I'm thinking of putting test results there for manual testing, but what else would fit well there? I prefer to have the docs under version control but maybe there's something apart from ordinary documentation that would be a good fit for the wiki?

You might like a "links" page to link to related projects.

Beyond that, there may be no need to plan ahead. One suggestion is to start the wiki, then add to it as you, or other users, think of things.

I think utilizing the wiki is good idea. In some cases it's easier to make a change to the wiki, rather than making changes to files within the main repo.

**Comment by SunyataZero** [comment]
Grateful for these suggestions, i've now added these:
* Building and Packaging Research (Other research could also get a page)
* Organizations and Postings on Websites
* Similar Applications
* Testamonials

**Comment by SunyataZero** [comment]
@andy5995 Do you think we should open up the wiki for editing by anyone? (Not just collaborators). This would make sense so that people without coding experience can add similar applications, suggestions for ideas, etc
