### ISSUE TITLE
Handle alternative click in systray

### ISSUE THREAD

**Issue by andy5995** [SunyataZero/mindfulness-at-the-computer#21]
@SunyataZero wrote in #5:

>The behavior i would like (for all platforms) is that the menu is shown on left click (and right click is ignored). Btw transmission-gtk also has the same behavior as redshift and matc does now

**Comment by SunyataZero** [comment]
https://stackoverflow.com/questions/46625306/xfce-and-qt-left-clicking-on-systray-does-nothing

**Comment by SunyataZero** [comment]
Behavior for different platforms:

Platform | Left click | Right click
---|---|---
XFCE | Nothing | Menu shown
LXDE | Menu shown | LXDE handles the click
Windows | Nothing | Menu shown

**Comment by SunyataZero** [comment]
https://ux.stackexchange.com/questions/111882/standard-for-using-the-system-tray

**Comment by SunyataZero** [comment]
I've been working on this issue today, there is a signal in Qt for the system tray called "activated" which can be used to intercept when someone clicks the tray. I haven't been able to get this working though even though i've followed the examples. I think the reason it doesn't work is that there is a bug for some desktop environments or os:es, see this issue: https://stackoverflow.com/questions/43657890/pyqt5-qsystemtrayicon-activated-signal-not-working

Maybe when upgrading to 5.9 (the latest Qt version) this will solve it for us, i don't know

**Comment by SunyataZero** [comment]
@andy5995 I've now updated to using PyQt 5.9 and still have the same problem. To see if the same problem appears on other platforms than the one i'm using (LXDE+Lubuntu) i've added a debug printout that prints this: "entered on_systray_activated". If you like you can start the program and click on the systray icon and then look for this message

**Comment by andy5995** [comment]
Yes, I get the debug message when I left click.

Let me know if you'd ever like me to test on KDE. I never use it but I think it's installed.

**Comment by SunyataZero** [comment]
Alright, then i can just show the same menu at left click as on right click (alternatively show the main window "restore" directly)

**Comment by andy5995** [comment]
I tried this with 2abcc37f5038b0869cb37930293211298d5208f7


```
Traceback (most recent call last):
  File "/home/andy/src/mindfulness-at-the-computer/mc/gui/main_window.py", line 208, in on_systray_activated
    self.tray_icon.contextMenu().popup()
TypeError: popup(self, QPoint, action: QAction = None): not enough arguments
Aborted
```

**Comment by SunyataZero** [comment]
Thank you for helping out, i have now experimented a bit with it myself (i don't have access to XFCE but can still test the popup line). The problem that i'm seeing is that the menu shown when triggering this manually is looking different from the standard systray menu. Therefore i'm changing so that "alternative clicking" on the systray icon instead normalizes the window. Hopefully this should work now in the latest version, can you try this as well?

Btw can you check to see what the debug output is after "entered on_systray_activated. i_reason = "

Grateful for help!

**Comment by andy5995** [comment]
It shows 3 when I click every second. It shows a pattern of 2,3,2,3,2,3 when I click very rapidly.

**Comment by SunyataZero** [comment]
Thank you, 2 means double click and 3 is "The system tray entry was clicked". See http://doc.qt.io/qt-5/qsystemtrayicon.html#ActivationReason-enum. This issue has been resolved since the "alternative click" now restores the window
