### ISSUE TITLE
Online help URL does not exist

### ISSUE THREAD

**Issue by andy5995** [SunyataZero/mindfulness-at-the-computer#23]
https://github.com/SunyataZero/mindfulness-at-the-computer/blob/df2011ef974ef4bafa17f944bea4d35a7e973a70/mc/gui/main_win.py#L258

As far as I can tell, the online help url doesn't exist, or was possibly changed (by me). I would fix this, but I'm not sure the best URL to put there.

**Comment by SunyataZero** [comment]
Thank you for reporting this, the url has changed and is now:

`https://sunyatazero.github.io/mindfulness-at-the-computer/user-guide.html`

This can be a newbie-friendly issue, so i've added the "first-timers-only" tag

**Comment by nicolehli** [comment]
first timer here and want to see if I can update the link as my first contribution. Can I try this out?

**Comment by SunyataZero** [comment]
@nicolehli Hi and welcome! Yes absolutely, please do. @andy5995 wrote [this guide](https://github.com/SunyataZero/mindfulness-at-the-computer/blob/master/CONTRIBUTING.md#pull-requests) describing the process. Kind Regards, Tord

**Comment by SunyataZero** [comment]
(I've invited you to [the chat room](https://gitter.im/mindfulness-at-the-computer/Lobby) if you like some more help with the pull request "PR" process. Actually @andy5995 is better at this but i'll also try to help as best i can)
