### ISSUE TITLE
LXDE only: System tray file icon "shown as missing" while showing notification

### ISSUE THREAD

**Issue by SunyataZero** [SunyataZero/mindfulness-at-the-computer#3]
This is a bug in Qt or PyQt

![](https://i.stack.imgur.com/2Kc6x.png)

I've posted a question here: https://stackoverflow.com/questions/45827951/missing-file-icon-is-shown-in-the-system-tray-when-running-showmessage-with-no

Qt version: 5.7.1, 5.9.0

This bug is not seen in XFCE (version 4.12)

**Comment by andy5995** [comment]
Hi @SunyataZero :) 

I don't understand the question. Do I have to delete a file to test this?

I see the app icon in the tray as normal, with the letters "BR" in the lower left quadrant.

```
INFO: Python version: 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118]
INFO: SQLite version: 3.16.2
INFO: PySQLite (Python module) version: 2.6.0
INFO: Qt version: 5.7.1
INFO: PyQt (Python module) version: 5.7
```

**Comment by SunyataZero** [comment]
@andy5995 Hi and thank you for helping out, it looks like this on LXDE when the breathing notification is shown: ![](https://i.stack.imgur.com/2Kc6x.png) Do you have this problem on XFCE?

**Comment by andy5995** [comment]
When the notification balloon pops up every 30 seconds, the icon does not change (XFCE 4.12)

**Comment by SunyataZero** [comment]
This is still a problem on LXDE, but since this is something that we cannot do anything about (an "upstream bug"), so i'm moving it to the wiki for now
