### ISSUE TITLE
Shortening the verb tense of Rest Actions

### ISSUE THREAD

**Issue by andy5995** [SunyataZero/mindfulness-at-the-computer#38]
This might be a desired change:

~~Making~~ Make a cup of tea
~~Opening~~ Open a window
~~Stretching~~ Stretch the arms

**Comment by SunyataZero** [comment]
I prefer the "less commanding" way of putting it, i want to put it in as non-threatening way as possible. Kind Regards, Tord

**Comment by andy5995** [comment]
Ah, I understand. :)
