### ISSUE TITLE
tray icon not responding, terminal output repeats, cpu usage at 100%

### ISSUE THREAD

**Issue by andy5995** [SunyataZero/mindfulness-at-the-computer#40]
I updated from the upstream couple hours ago.

I ran it and walked away for a while.

I see my cpu usage for `python3` is at 100%.

Messages keep repeating in the terminal. It looks like they're not. I can only tell they are repeating quickly when I press `ctrl-z`, and then enter `fg` again.

The icon in the tray is non-responsive.

```
DEBUG: ret_value_bool = False
DEBUG: icon_file_name_str = icon-r.png
DEBUG: icon_path_str = /home/andy/src/mindfulness-at-the-computer/icons/icon-r.png
DEBUG: ret_value_bool = False
DEBUG: icon_file_name_str = icon-r.png
DEBUG: icon_path_str = /home/andy/src/mindfulness-at-the-computer/icons/icon-r.png
DEBUG: ret_value_bool = False
DEBUG: icon_file_name_str = icon-r.png
DEBUG: icon_path_str = /home/andy/src/mindfulness-at-the-computer/icons/icon-r.png
DEBUG: ret_value_bool = False
DEBUG: icon_file_name_str = icon-r.png
DEBUG: icon_path_str = /home/andy/src/mindfulness-at-the-computer/icons/icon-r.png
DEBUG: ret_value_bool = False
DEBUG: icon_file_name_str = icon-r.png
DEBUG: icon_path_str = /home/andy/src/mindfulness-at-the-computer/icons/icon-r.png
```

Here's the output when I use `ctrl-c`
```
DEBUG: ret_value_bool = False
DEBUG: icon_file_name_str = icon-r.png
DEBUG: icon_path_str = /home/andy/src/mindfulness-at-the-computer/icons/icon-r.png
^CTraceback (most recent call last):
  File "/home/andy/src/mindfulness-at-the-computer/mc/gui/main_window.py", line 227, in on_rest_settings_changed
    self.update_gui(mc.mc_global.EventSource.rest_settings_changed)
  File "/home/andy/src/mindfulness-at-the-computer/mc/gui/main_window.py", line 425, in update_gui
    self.rest_actions_widget.update_gui()
  File "/home/andy/src/mindfulness-at-the-computer/mc/gui/rest_action_list_dock.py", line 177, in update_gui
    self.list_widget.addItem(list_item)
KeyboardInterrupt
Aborted
```

**Comment by SunyataZero** [comment]
@andy5995 Yes i've changed some gui_update functions and there must have been a loop here (there's a big risk of that), can you try to clone the latest version? Kind Regards, Tord

**Comment by andy5995** [comment]
I replicated a second time using https://github.com/SunyataZero/mindfulness-at-the-computer/commit/13b2b6933090dd37f8595748f7705493026c3096

I didn't make a note of the hash for the first time.

I'll try again (906bcfd8f8167bb61ed8ff026e5bc38a9959442b)

**Comment by SunyataZero** [comment]
Okay strange, i am running the latest and there is almost no cpu usage and no debug output. In a way i am not surprised though because of the changes i've made to the gui update system, there is a high risk of loops. I will try and rethink how i can better organize it to reduce the risk of this type of problem

**Comment by SunyataZero** [comment]
@andy5995 Alright i've now made some changes to the GUI update system, specifically trying to avoid loops. Can you try to run the latest version now? Kind Regards, Tord

**Comment by andy5995** [comment]
>I'll try again (906bcfd8f8167bb61ed8ff026e5bc38a9959442b)

Same result

Trying again with 44f7413250c342d0095887cc5125fb9b2aeed2af ....

**Comment by andy5995** [comment]
It's not freezing anymore. Good fix!

**Comment by SunyataZero** [comment]
Okay, thank you for finding this bug and staying with me through the process. It's strange though that you saw the bug but not me, we are running the application on almost the same system. Perhaps there was a race condition or something. Kind Regards, Tord
