### ISSUE TITLE
How to deal with systems without notifications?

### ISSUE THREAD

**Issue by SunyataZero** [SunyataZero/mindfulness-at-the-computer#43]
It seems not all Mac systems need to have growl. A Mac user wrote that it seems like Qt talks directly with the Mac notification system

We may want to show another type of warning (rather than a log warning as now) when the user starts the application and does not have support for showing notifications

**Comment by taniaReyesM** [comment]
Maybe the notification can be sent to their mobile phone

**Comment by SunyataZero** [comment]
Closing this issue since we have recently removed the notifications from the application (instead using a custom and interactive dialog that the user can breathe with)
