### ISSUE TITLE
Exchange an int counter for enumerate

### ISSUE THREAD

**Issue by SunyataZero** [SunyataZero/mindfulness-at-the-computer#60]
Right now we are using int counters in while loops, but we would like to use `enumerate` instead

[Official Python documentation for enumerate](https://docs.python.org/3/library/functions.html#enumerate)

[Explanation by Martijn Pieters on SO](https://stackoverflow.com/a/22171593/2525237)

To find a place where enumerate can be used please search for `count` in the code files, this should give a few results. Please choose one and remove the counter and instead put something like this there instead:

```
for count_int, element in enumerate(element_list):
```

***

If you like the project you can help out by "starring" the project <3 This will make it easier to find the project for others

**Comment by SunyataZero** [comment]
Here is one place where you can fix this: [The add_from_dialog function in the breathing_widget.py file](https://github.com/SunyataZero/mindfulness-at-the-computer/blob/cb4de87e891728a64f32b6c722cd4e427dda2337/mc/gui/breathing_widget.py#L199)

```
    def add_from_dialog(self, i_ilist, i_olist):
        self.new_cycle_bool = True
        counter_int = 0
        while len(i_olist) > counter_int:
            # -using ob here ensures that we only add when there are complete breathing cycles
            self.add_new_breathing_rect(
                mc.mc_global.BreathingState.breathing_in,
                i_ilist[counter_int],
                mc.mc_global.BreathingVisType.popup_dialog
            )
            self.add_new_breathing_rect(
                mc.mc_global.BreathingState.breathing_out,
                i_olist[counter_int],
                mc.mc_global.BreathingVisType.popup_dialog
            )
            counter_int += 1
        self.new_cycle_bool = True
```

**Comment by hangZH03** [comment]
Hello, as a code newbie I'd like to try this , may I? @SunyataZero

**Comment by SunyataZero** [comment]
@hangZH03 Hi and welcome! Yes please go ahead. @jmlgh is working right now on the section of code in the comment above (file: breathing_widget.py) but there is also [this code that needs to be fixed inside main_window.py](https://github.com/SunyataZero/mindfulness-at-the-computer/blob/master/mc/gui/main_window.py#L179):

```
        count_int = 0
        self.system_tray.tray_phrase_qaction_list.clear()
        for l_phrase in mc.model.PhrasesM.get_all():
            INDENTATION_STR = "  "
            ACTIVE_MARKER_STR = "•"
            INACTIVE_MARKER_STR = " "
            active_or_inactive_str = INACTIVE_MARKER_STR
            if l_phrase.id_int == mc.mc_global.active_phrase_id_it:
                active_or_inactive_str = ACTIVE_MARKER_STR
            tray_phrase_qaction = QtWidgets.QAction(active_or_inactive_str + INDENTATION_STR + l_phrase.title_str)
            tray_phrase_qaction.triggered.connect(
                functools.partial(
                    self.phrase_list_widget.on_new_row_selected_from_system_tray,
                    l_phrase.id_int
                )
            )
            self.system_tray.tray_phrase_qaction_list.append(tray_phrase_qaction)
            # self.tray_phrase_qaction = QtWidgets.QAction(l_phrase.title_str)
            self.tray_menu.addAction(tray_phrase_qaction)
            count_int += 1
            if count_int >= 5:
                break
```

If you like you can join us on our [gitter chat](https://gitter.im/mindfulness-at-the-computer/Lobby) and ask any questions about the coding or the process of using git

Kind Regards,
Tord

**Comment by hangZH03** [comment]
Ok, I would like to try this, thanks
