### ISSUE TITLE
Mouse is moved even when a mouse button is pressed down

### ISSUE THREAD

**Issue by SunyataZero** [SunyataZero/mindfulness-at-the-computer#87]
1. Mouse button is pressed down
2. There is a timeout and the breathing dialog is shown
3. The mouse button is moved to the dialog area

This might result in frustrating behavior, for example the user may be setting the volume in an application by pressing down the mouse button and moving the mouse and then this happens which can lead to the volume being min or max

**Comment by srukle** [comment]
Do you mean when you move your mouse into the dialogue box, like the white box with the bar graph?

**Comment by SunyataZero** [comment]
@srukle When the user has the mouse button pressed down, and then the breathing dialog is shown - moving the mouse cursor away - this can cause some funny effects like if you are dragging a window it will appear far down, or if you are using a vector-based drawing program. I'm tired now but will try to update the description with more info another time. Kind Regards, Tord

**Comment by srukle** [comment]
@SunyataZero I cannot read your commit message. Could you clarify why the ticket was closed please? Thank you.

**Comment by SunyataZero** [comment]
@srukle Hi, i'm glad you are interested in this project and i'll be happy to explain: The functionality of moving the mouse pointer has been removed now so this issue is no longer relevant

What i tried before removing this functionality:
* I did research to see if there was any way to send a global "mouseup" programatically (this isn't possible)
* I tried detecting the global mouse button state using [this function](http://doc.qt.io/qt-5/qguiapplication.html#mouseButtons). The name leads us to believe that this can be detected, but reading the description makes it clear that this may not work always, and it doesn't for us (i did some experimentation)
