### ISSUE TITLE
docs missing at https://sunyatazero.github.io/participate.html

### ISSUE THREAD

**Issue by srukle** [SunyataZero/mindfulness-at-the-computer#88]
Page is a 404.

To go to page, follow the path here:
https://sunyatazero.github.io/mindfulness-at-the-computer/

click on participate

**Comment by rustyday** [comment]
The URL is wrong, currently points to: https://sunyatazero.github.io/participate.html
Should be: https://sunyatazero.github.io/mindfulness-at-the-computer/participate.html

**Comment by SunyataZero** [comment]
Thank you for finding this, i've now pushed a bug fix which resolves this issue. Kind Regards, Tord
