### ISSUE TITLE
[Multiple desktops][MacOS] Reminders not shown in the current desktop

### ISSUE THREAD

**Issue by SunyataZero** [SunyataZero/mindfulness-at-the-computer#90]
http://doc.qt.io/qt-5/qdesktopwidget.html

**Comment by SunyataZero** [comment]
I don't see this on my LXDE system, have written in the gitter lobby about this asking people to test the latest code

**Comment by mbed67** [comment]
After pulling the latest changes, the reminders are indeed shown in the current desktop. However, when I click on the close button, the application crashes with the following message
```Traceback (most recent call last):
  File "/Users/marieke/myprojects/mindfulness-at-the-computer/mc/gui/main_window.py", line 367, in on_breathing_dialog_closed
    self.breathing_widget.add_from_dialog(i_ib_list, i_ob_list)
AttributeError: 'MatcMainWindow' object has no attribute 'breathing_widget'```
